name: interactive_swipe_guide
description: "Package for creating swipe-driven onboarding or tutorial overlays in Flutter. (For tinder like dating apps that require swiping left, right, up, and down)"
version: 0.0.1
homepage: https://github.com/SahilSelfmade/interactive_swipe_guide
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
# flutter:
